run_name: "full_musicnet_groups_of_20"
transcriber_ckpt: "ckpts/model-70.pt"
multi_ckpt: False # Flag if the ckpt was trained on pitch only or instrument-sensitive. The provided checkpoints were trained on pitch only.

checkpoint_interval: 6 # how often to save checkpoint
batch_size: 8

# iterations = 1000 # per epoch
iterations: 100
learning_rate: 0.0001
learning_rate_decay_steps: 10000
clip_gradient_norm: 3
# epochs: 15
epochs: 15